package com.perceptive.epm.perkolcentral.hibernate.pojo;
// Generated Sep 23, 2012 6:50:23 PM by Hibernate Tools 3.2.4.GA



/**
 * Employeerolemapping generated by hbm2java
 */
public class Employeerolemapping  implements java.io.Serializable {


     private Long employeeRoleMappingId;
     private Employee employee;
     private Rolemaster rolemaster;

    public Employeerolemapping() {
    }

    public Employeerolemapping(Employee employee, Rolemaster rolemaster) {
       this.employee = employee;
       this.rolemaster = rolemaster;
    }
   
    public Long getEmployeeRoleMappingId() {
        return this.employeeRoleMappingId;
    }
    
    public void setEmployeeRoleMappingId(Long employeeRoleMappingId) {
        this.employeeRoleMappingId = employeeRoleMappingId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Rolemaster getRolemaster() {
        return this.rolemaster;
    }
    
    public void setRolemaster(Rolemaster rolemaster) {
        this.rolemaster = rolemaster;
    }




}


