package com.perceptive.epm.perkolcentral.hibernate.pojo;
// Generated Sep 23, 2012 6:50:23 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {


    private long employeeId;
    private String employeeUid;
    private String employeeName;
    private String email;
    private String jobTitle;
    private String mobileNumber;
    private String manager;
    private String managerEmail;
    private String extensionNum;
    private String workspace;
    private boolean isActive;
    private Set<Employeelicensemapping> employeelicensemappings = new HashSet<Employeelicensemapping>(0);
    private Set<Employeegroupmap> employeegroupmaps = new HashSet<Employeegroupmap>(0);
    private Set<Imagenowlicenses> imagenowlicensesesForRequestedByEmployeeId = new HashSet<Imagenowlicenses>(0);
    private Set<Imagenowlicenses> imagenowlicensesesForProvidedByEmployeeId = new HashSet<Imagenowlicenses>(0);
    private Set<Employeerolemapping> employeerolemappings = new HashSet<Employeerolemapping>(0);

    public Employee() {
    }


    public Employee(long employeeId, String employeeUid, String employeeName, String email, boolean isActive) {
        this.employeeId = employeeId;
        this.employeeUid = employeeUid;
        this.employeeName = employeeName;
        this.email = email;
        this.isActive = isActive;
    }

    public Employee(long employeeId, String employeeUid, String employeeName, String email, String jobTitle, String mobileNumber, String manager, String managerEmail, String extensionNum, String workspace, boolean isActive, Set<Employeelicensemapping> employeelicensemappings, Set<Employeegroupmap> employeegroupmaps, Set<Imagenowlicenses> imagenowlicensesesForRequestedByEmployeeId, Set<Imagenowlicenses> imagenowlicensesesForProvidedByEmployeeId, Set<Employeerolemapping> employeerolemappings) {
        this.employeeId = employeeId;
        this.employeeUid = employeeUid;
        this.employeeName = employeeName;
        this.email = email;
        this.jobTitle = jobTitle;
        this.mobileNumber = mobileNumber;
        this.manager = manager;
        this.managerEmail = managerEmail;
        this.extensionNum = extensionNum;
        this.workspace = workspace;
        this.isActive = isActive;
        this.employeelicensemappings = employeelicensemappings;
        this.employeegroupmaps = employeegroupmaps;
        this.imagenowlicensesesForRequestedByEmployeeId = imagenowlicensesesForRequestedByEmployeeId;
        this.imagenowlicensesesForProvidedByEmployeeId = imagenowlicensesesForProvidedByEmployeeId;
        this.employeerolemappings = employeerolemappings;
    }

    public long getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }

    public String getEmployeeUid() {
        return this.employeeUid;
    }

    public void setEmployeeUid(String employeeUid) {
        this.employeeUid = employeeUid;
    }

    public String getEmployeeName() {
        return this.employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getMobileNumber() {
        return this.mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getManager() {
        return this.manager;
    }

    public void setManager(String manager) {
        this.manager = manager;
    }

    public String getManagerEmail() {
        return managerEmail;
    }

    public void setManagerEmail(String managerEmail) {
        this.managerEmail = managerEmail;
    }

    public String getExtensionNum() {
        return this.extensionNum;
    }

    public void setExtensionNum(String extensionNum) {
        this.extensionNum = extensionNum;
    }

    public String getWorkspace() {
        return this.workspace;
    }

    public void setWorkspace(String workspace) {
        this.workspace = workspace;
    }

    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public Set<Employeelicensemapping> getEmployeelicensemappings() {
        return this.employeelicensemappings;
    }

    public void setEmployeelicensemappings(Set<Employeelicensemapping> employeelicensemappings) {
        this.employeelicensemappings = employeelicensemappings;
    }

    public Set<Employeegroupmap> getEmployeegroupmaps() {
        return this.employeegroupmaps;
    }

    public void setEmployeegroupmaps(Set<Employeegroupmap> employeegroupmaps) {
        this.employeegroupmaps = employeegroupmaps;
    }

    public Set<Imagenowlicenses> getImagenowlicensesesForRequestedByEmployeeId() {
        return this.imagenowlicensesesForRequestedByEmployeeId;
    }

    public void setImagenowlicensesesForRequestedByEmployeeId(Set<Imagenowlicenses> imagenowlicensesesForRequestedByEmployeeId) {
        this.imagenowlicensesesForRequestedByEmployeeId = imagenowlicensesesForRequestedByEmployeeId;
    }

    public Set<Imagenowlicenses> getImagenowlicensesesForProvidedByEmployeeId() {
        return this.imagenowlicensesesForProvidedByEmployeeId;
    }

    public void setImagenowlicensesesForProvidedByEmployeeId(Set<Imagenowlicenses> imagenowlicensesesForProvidedByEmployeeId) {
        this.imagenowlicensesesForProvidedByEmployeeId = imagenowlicensesesForProvidedByEmployeeId;
    }

    public Set<Employeerolemapping> getEmployeerolemappings() {
        return this.employeerolemappings;
    }

    public void setEmployeerolemappings(Set<Employeerolemapping> employeerolemappings) {
        this.employeerolemappings = employeerolemappings;
    }


}


