package com.perceptive.epm.perkolcentral.hibernate.pojo;
// Generated Sep 23, 2012 6:50:23 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private Integer groupId;
     private String groupName;
     private String groupDescription;
     private Boolean isActive;
     private Boolean isRallyGroup;
     private Set<Imagenowlicenses> imagenowlicenseses = new HashSet<Imagenowlicenses>(0);
     private Set<Employeegroupmap> employeegroupmaps = new HashSet<Employeegroupmap>(0);

    public Groups() {
    }

	
    public Groups(String groupName) {
        this.groupName = groupName;
    }
    public Groups(String groupName, String groupDescription, Boolean isActive, Boolean isRallyGroup, Set<Imagenowlicenses> imagenowlicenseses, Set<Employeegroupmap> employeegroupmaps) {
       this.groupName = groupName;
       this.groupDescription = groupDescription;
       this.isActive = isActive;
       this.isRallyGroup = isRallyGroup;
       this.imagenowlicenseses = imagenowlicenseses;
       this.employeegroupmaps = employeegroupmaps;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getGroupDescription() {
        return this.groupDescription;
    }
    
    public void setGroupDescription(String groupDescription) {
        this.groupDescription = groupDescription;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Boolean getIsRallyGroup() {
        return this.isRallyGroup;
    }
    
    public void setIsRallyGroup(Boolean isRallyGroup) {
        this.isRallyGroup = isRallyGroup;
    }
    public Set<Imagenowlicenses> getImagenowlicenseses() {
        return this.imagenowlicenseses;
    }
    
    public void setImagenowlicenseses(Set<Imagenowlicenses> imagenowlicenseses) {
        this.imagenowlicenseses = imagenowlicenseses;
    }
    public Set<Employeegroupmap> getEmployeegroupmaps() {
        return this.employeegroupmaps;
    }
    
    public void setEmployeegroupmaps(Set<Employeegroupmap> employeegroupmaps) {
        this.employeegroupmaps = employeegroupmaps;
    }




}


