package com.perceptive.epm.perkolcentral.hibernate.pojo;
// Generated Sep 23, 2012 6:50:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * Imagenowlicenses generated by hbm2java
 */
public class Imagenowlicenses  implements java.io.Serializable {


     private String imageNowLicenseRequestId;
     private Employee employeeByProvidedByEmployeeId;
     private Groups groups;
     private Employee employeeByRequestedByEmployeeId;
     private String imageNowVersion;
     private long numberOfLicenses;
     private String fileName;
     private Date licenseRequestedOn;
     private Date licenseProvidedOn;
     private boolean isProvided;

    public Imagenowlicenses() {
    }

	
    public Imagenowlicenses(String imageNowLicenseRequestId, Groups groups, Employee employeeByRequestedByEmployeeId, String imageNowVersion, long numberOfLicenses, String fileName, Date licenseRequestedOn, boolean isProvided) {
        this.imageNowLicenseRequestId = imageNowLicenseRequestId;
        this.groups = groups;
        this.employeeByRequestedByEmployeeId = employeeByRequestedByEmployeeId;
        this.imageNowVersion = imageNowVersion;
        this.numberOfLicenses = numberOfLicenses;
        this.fileName = fileName;
        this.licenseRequestedOn = licenseRequestedOn;
        this.isProvided = isProvided;
    }
    public Imagenowlicenses(String imageNowLicenseRequestId, Employee employeeByProvidedByEmployeeId, Groups groups, Employee employeeByRequestedByEmployeeId, String imageNowVersion, long numberOfLicenses, String fileName, Date licenseRequestedOn, Date licenseProvidedOn, boolean isProvided) {
       this.imageNowLicenseRequestId = imageNowLicenseRequestId;
       this.employeeByProvidedByEmployeeId = employeeByProvidedByEmployeeId;
       this.groups = groups;
       this.employeeByRequestedByEmployeeId = employeeByRequestedByEmployeeId;
       this.imageNowVersion = imageNowVersion;
       this.numberOfLicenses = numberOfLicenses;
       this.fileName = fileName;
       this.licenseRequestedOn = licenseRequestedOn;
       this.licenseProvidedOn = licenseProvidedOn;
       this.isProvided = isProvided;
    }
   
    public String getImageNowLicenseRequestId() {
        return this.imageNowLicenseRequestId;
    }
    
    public void setImageNowLicenseRequestId(String imageNowLicenseRequestId) {
        this.imageNowLicenseRequestId = imageNowLicenseRequestId;
    }
    public Employee getEmployeeByProvidedByEmployeeId() {
        return this.employeeByProvidedByEmployeeId;
    }
    
    public void setEmployeeByProvidedByEmployeeId(Employee employeeByProvidedByEmployeeId) {
        this.employeeByProvidedByEmployeeId = employeeByProvidedByEmployeeId;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public Employee getEmployeeByRequestedByEmployeeId() {
        return this.employeeByRequestedByEmployeeId;
    }
    
    public void setEmployeeByRequestedByEmployeeId(Employee employeeByRequestedByEmployeeId) {
        this.employeeByRequestedByEmployeeId = employeeByRequestedByEmployeeId;
    }
    public String getImageNowVersion() {
        return this.imageNowVersion;
    }
    
    public void setImageNowVersion(String imageNowVersion) {
        this.imageNowVersion = imageNowVersion;
    }
    public long getNumberOfLicenses() {
        return this.numberOfLicenses;
    }
    
    public void setNumberOfLicenses(long numberOfLicenses) {
        this.numberOfLicenses = numberOfLicenses;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Date getLicenseRequestedOn() {
        return this.licenseRequestedOn;
    }
    
    public void setLicenseRequestedOn(Date licenseRequestedOn) {
        this.licenseRequestedOn = licenseRequestedOn;
    }
    public Date getLicenseProvidedOn() {
        return this.licenseProvidedOn;
    }
    
    public void setLicenseProvidedOn(Date licenseProvidedOn) {
        this.licenseProvidedOn = licenseProvidedOn;
    }
    public boolean isIsProvided() {
        return this.isProvided;
    }
    
    public void setIsProvided(boolean isProvided) {
        this.isProvided = isProvided;
    }




}


