package com.perceptive.epm.perkolcentral.hibernate.pojo;
// Generated Sep 23, 2012 6:50:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * Licensepurchase generated by hbm2java
 */
public class Licensepurchase  implements java.io.Serializable {


     private Long licensePurchaseId;
     private Licensemaster licensemaster;
     private Date licensePurchaseDate;
     private int numberOfLicenses;
     private String licensePurchaseDescription;

    public Licensepurchase() {
    }

	
    public Licensepurchase(Licensemaster licensemaster, Date licensePurchaseDate, int numberOfLicenses) {
        this.licensemaster = licensemaster;
        this.licensePurchaseDate = licensePurchaseDate;
        this.numberOfLicenses = numberOfLicenses;
    }
    public Licensepurchase(Licensemaster licensemaster, Date licensePurchaseDate, int numberOfLicenses, String licensePurchaseDescription) {
       this.licensemaster = licensemaster;
       this.licensePurchaseDate = licensePurchaseDate;
       this.numberOfLicenses = numberOfLicenses;
       this.licensePurchaseDescription = licensePurchaseDescription;
    }
   
    public Long getLicensePurchaseId() {
        return this.licensePurchaseId;
    }
    
    public void setLicensePurchaseId(Long licensePurchaseId) {
        this.licensePurchaseId = licensePurchaseId;
    }
    public Licensemaster getLicensemaster() {
        return this.licensemaster;
    }
    
    public void setLicensemaster(Licensemaster licensemaster) {
        this.licensemaster = licensemaster;
    }
    public Date getLicensePurchaseDate() {
        return this.licensePurchaseDate;
    }
    
    public void setLicensePurchaseDate(Date licensePurchaseDate) {
        this.licensePurchaseDate = licensePurchaseDate;
    }
    public int getNumberOfLicenses() {
        return this.numberOfLicenses;
    }
    
    public void setNumberOfLicenses(int numberOfLicenses) {
        this.numberOfLicenses = numberOfLicenses;
    }
    public String getLicensePurchaseDescription() {
        return this.licensePurchaseDescription;
    }
    
    public void setLicensePurchaseDescription(String licensePurchaseDescription) {
        this.licensePurchaseDescription = licensePurchaseDescription;
    }




}


