package com.perceptive.epm.perkolcentral.hibernate.pojo;
// Generated Sep 23, 2012 6:50:23 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Licensemaster generated by hbm2java
 */
public class Licensemaster  implements java.io.Serializable {


     private Long licenseTypeId;
     private String licenseTypeName;
     private String licenseTypeDescription;
     private Set<Employeelicensemapping> employeelicensemappings = new HashSet<Employeelicensemapping>(0);
     private Set<Licensepurchase> licensepurchases = new HashSet<Licensepurchase>(0);

    public Licensemaster() {
    }

	
    public Licensemaster(String licenseTypeName) {
        this.licenseTypeName = licenseTypeName;
    }
    public Licensemaster(String licenseTypeName, String licenseTypeDescription, Set<Employeelicensemapping> employeelicensemappings, Set<Licensepurchase> licensepurchases) {
       this.licenseTypeName = licenseTypeName;
       this.licenseTypeDescription = licenseTypeDescription;
       this.employeelicensemappings = employeelicensemappings;
       this.licensepurchases = licensepurchases;
    }
   
    public Long getLicenseTypeId() {
        return this.licenseTypeId;
    }
    
    public void setLicenseTypeId(Long licenseTypeId) {
        this.licenseTypeId = licenseTypeId;
    }
    public String getLicenseTypeName() {
        return this.licenseTypeName;
    }
    
    public void setLicenseTypeName(String licenseTypeName) {
        this.licenseTypeName = licenseTypeName;
    }
    public String getLicenseTypeDescription() {
        return this.licenseTypeDescription;
    }
    
    public void setLicenseTypeDescription(String licenseTypeDescription) {
        this.licenseTypeDescription = licenseTypeDescription;
    }
    public Set<Employeelicensemapping> getEmployeelicensemappings() {
        return this.employeelicensemappings;
    }
    
    public void setEmployeelicensemappings(Set<Employeelicensemapping> employeelicensemappings) {
        this.employeelicensemappings = employeelicensemappings;
    }
    public Set<Licensepurchase> getLicensepurchases() {
        return this.licensepurchases;
    }
    
    public void setLicensepurchases(Set<Licensepurchase> licensepurchases) {
        this.licensepurchases = licensepurchases;
    }




}


