package com.perceptive.epm.perkolcentral.hibernate.pojo;
// Generated Sep 23, 2012 6:50:23 PM by Hibernate Tools 3.2.4.GA



/**
 * Pages generated by hbm2java
 */
public class Pages  implements java.io.Serializable {


     private String pageId;
     private String pageName;
     private String pageUrl;
     private String pageDescription;

    public Pages() {
    }

	
    public Pages(String pageId, String pageName, String pageUrl) {
        this.pageId = pageId;
        this.pageName = pageName;
        this.pageUrl = pageUrl;
    }
    public Pages(String pageId, String pageName, String pageUrl, String pageDescription) {
       this.pageId = pageId;
       this.pageName = pageName;
       this.pageUrl = pageUrl;
       this.pageDescription = pageDescription;
    }
   
    public String getPageId() {
        return this.pageId;
    }
    
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }
    public String getPageUrl() {
        return this.pageUrl;
    }
    
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }
    public String getPageDescription() {
        return this.pageDescription;
    }
    
    public void setPageDescription(String pageDescription) {
        this.pageDescription = pageDescription;
    }




}


