package com.perceptive.epm.perkolcentral.hibernate.pojo;
// Generated Sep 23, 2012 6:50:23 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rolemaster generated by hbm2java
 */
public class Rolemaster  implements java.io.Serializable {


     private Long roleId;
     private String roleName;
     private Set<Employeerolemapping> employeerolemappings = new HashSet<Employeerolemapping>(0);

    public Rolemaster() {
    }

	
    public Rolemaster(String roleName) {
        this.roleName = roleName;
    }
    public Rolemaster(String roleName, Set<Employeerolemapping> employeerolemappings) {
       this.roleName = roleName;
       this.employeerolemappings = employeerolemappings;
    }
   
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Set<Employeerolemapping> getEmployeerolemappings() {
        return this.employeerolemappings;
    }
    
    public void setEmployeerolemappings(Set<Employeerolemapping> employeerolemappings) {
        this.employeerolemappings = employeerolemappings;
    }




}


